### ISSUE TITLE
Special scope for the class that is being extended

### ISSUE THREAD

**Issue by aziz** [bathos/Ecmascript-Sublime#12]
```
class AddFeed extends Component
```

`Component` should have a special scope not just `variable.other.readwrite.initCap.es`.
something like: `entity.name.class.extended.es`

**Comment by bathos** [comment]
Good idea, this can be done. However, you should note that the super production is an open-ended assignment expression. It would not be an entity.name, because it can be anything at all; meta.super-expression would be consistent with conventions. I try to avoid meta when possible, but this is a good case for it I think.

**Comment by bathos** [comment]
`meta.super-expression` is now applied across the super expression
