### ISSUE TITLE
Package Browser Install

### ISSUE THREAD

**Issue by cwbit** [bathos/Ecmascript-Sublime#2]
Hi! Not really so much an issue maybe, but this package does not come up in the in-app package control install menu.

Not only does this look like exactly what I need, but it looks like you put a ton of time into it!

Is installation via the package manager not supported?

Thanks!

**Comment by bathos** [comment]
The package is called Ecmascript Syntax on Package Control. However it requires Sublime version 3084 or higher ... and the latest public version of Sublime 3 is 3083 :(

PackageControl doesn't show packages unless your Sublime meets the requirements, so that's the most likely reason for not seeing it in the list. If that is the reason, you can download the [latest dev channel release](http://www.sublimetext.com/3dev) and then this package will become installable / usable. But there's a catch: unlike the public 2 & 3 releases, the dev channel versions only work for registered users.

I'm really hoping there'll be a new official release of Sublime 3 soon, because I don't think many people use the dev builds. To date, only 50 people downloaded Ecmascript Sublime, and three of them are me. Then again, that might just mean most people are not as gung ho about semantic brace coloring as I am :)

**Comment by akurtz** [comment]
+1  @bathos: You, sir, have to be one of the most detail-oriented devs I've seen on Github.  Kudos.  Really sorry you went to all this trouble with so few people able to use it.  It looks awesome and I'd love to try it, but at 8 months since the last "stable" beta release and 4+ months with nary a peep from the developer with no response to bug reports, I'm afraid ST is becoming abandonware.  Hope I'm wrong.  If we see another release in the near future then I'll register and get on the dev channel.

**Comment by bathos** [comment]
Thanks @akurtz.

Yeah, the state of ST is pretty worrisome. Seems like a lot of folks are jumping ship for Atom, but as far as I can tell, Atom only supports tmLanguage, so there's no simple way for me to port this without losing most of what made it cool. Since Atom is purportedly fully "hackable" I wonder if it's be possible to write an alternative highlighting engine for it with the same power as sublime syntax...?

Recently I've been working on an [experimental version](https://github.com/bathos/Ecmascript-Sublime/blob/experiment/ecmascript-scoped.sublime-syntax) of the syntax that applies scopes in such a way that one can write themes targeting by depth of nested function / lexical scope instead of, or in addition to, traditional coloring targets.

**Comment by akurtz** [comment]
@bathos You da real MVP.  Don't let this die when ST goes the way of Textmate.
