### ISSUE TITLE
Arguments following spread

### ISSUE THREAD

**Issue by barneycarroll** [bathos/Ecmascript-Sublime#3]
Thanks for the fantastic work on this. My terse method declarations and bind operations read sensible now. It's a huge boon!

I've spotted the following problems, not sure if it's an issue with themes or the parser - Carthage doesn't suffer (although I find almost everything except for operators and functions impossible to distinguish in Carthage anyway). All these screens were taken in Monokai, but the same problem is visible with Excelsior & Villa-Lobos.

Any arguments following a spread don't play well, see line 125:
![screenshot from 2015-10-28 11-11-54](https://cloud.githubusercontent.com/assets/83627/10786892/de7273a4-7d64-11e5-81eb-3ba84de2e8b9.png)

**Comment by bathos** [comment]
Thanks. I tried to nail this quick the other day since I only had a minute, and accidentally did params instead of args. Revising now.

**Comment by barneycarroll** [comment]
Thanks! Incidentally, this reminded me how irritated I am that a leading rest operation is illegal in the first place. Don't suppose you've got any insight on why this is the case?

**Comment by bathos** [comment]
I bet there are ES Discuss records about that. Perhaps it would create some hidden complexity. Superficially, permitting a "rightward" mapping is not ambiguous:

    function poop(...rest, last) {}
    function poop(...rest, penultimate, last) {}

The first thing I can think of is that it does require some new grammar, because this, along with any other parameter declaration with two rests, is nonsensical:

   function poop(...wat, ...no) {}

On the other hand, this is actually unambiguous:

  function poop(first, ...middle, last) {}

So they could have written the grammar such that any given parameter declaration would contain zero or one rest parameters. I don't think this would have required any hoop jumping, actually -- no cover grammars or anything like that -- so I doubt grammatical complexity was the issue.

So perhaps it has something to do with how function parameters are implemented internally -- maybe it would be somehow disruptive that, if non-terminal rests were permitted, *non-*rest parameters would no longer have specific indices. But I'm just guessing here; for all I know, nobody brought it up? I'm pretty clueless about the internal mechanics for outfitting functions.

**Comment by bathos** [comment]
Other thoughts: In your own code, you can implement a simple util for supporting right-to-left rest-params. (More complex forms wouldn't be so easy to represent, though):

```js
const reversedRest = fn => {
  const ln = fn.length;
  
  return (...args) => {
    const rest  = args.slice(0, -ln);
    const named = args.reverse().slice(0, ln);
    return fn(...named, ...rest);
  };
}

const example = reversedRest((tail, ...rest) =>
  `the tail is "${ tail }"; there are ${ rest.length } members prior (${ rest })`
);

console.log(example('a', 'b', 'c', 'd'));
```

On [Babel REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=const%20reversedRest%20%3D%20fn%20%3D%3E%20%7B%0A%20%20const%20ln%20%3D%20fn.length%3B%0A%20%20%0A%20%20return%20(...args)%20%3D%3E%20%7B%0A%20%20%20%20const%20rest%20%20%3D%20args.slice(0%2C%20-ln)%3B%0A%20%20%20%20const%20named%20%3D%20args.reverse().slice(0%2C%20ln)%3B%0A%20%20%20%20return%20fn(...named%2C%20...rest)%3B%0A%20%20%7D%3B%0A%7D%0A%0Aconst%20example%20%3D%20reversedRest((tail%2C%20...rest)%20%3D%3E%0A%20%20%60the%20tail%20is%20%22%24%7B%20tail%20%7D%22%3B%20there%20are%20%24%7B%20rest.length%20%7D%20members%20prior%20(%24%7B%20rest%20%7D)%60%0A)%3B%0A%0Aconsole.log(example('a'%2C%20'b'%2C%20'c'%2C%20'd'))%3B)
