### ISSUE TITLE
Error loading colour scheme Packages/Ecmascript Syntax/excelsior.tmTheme

### ISSUE THREAD

**Issue by OdinTech3** [bathos/Ecmascript-Sublime#60]
When I try to use the excelsior theme from the Ecmascript Sublime Package, I get this:

![screen shot 2018-10-19 at 7 07 54 am](https://user-images.githubusercontent.com/14257815/47214992-c3857700-d36d-11e8-8dbd-b2abbcc7446e.png)

Running on MacOS  High Seirra 10.13.6 and using Sublime Text Build Version 3180

**Comment by blake-regalia** [comment]
Thanks for the report. The excelsior file was recently moved to another location. As a workaround, you can simply choose that UI color scheme which is located at `Packages/Ecmascript Syntax/nested/build/ecmascript` (see 2nd list item in screenshot).
<img width="604" alt="screen shot 2018-10-19 at 10 36 18 am" src="https://user-images.githubusercontent.com/1456400/47234505-f0945280-d38a-11e8-88b5-dabaed3f7b0f.png">


The reason there are two files is that this color scheme is now generated during the build process. The location of the old file is now a symbolic link to the generated file, but I can see this is causing an issue when the directory is bundled into a `.sublime-package` archive. I suppose a remedy for this could be to add those two paths to the [`files_to_ignore` settings](https://packagecontrol.io/docs/settings#setting-files_to_ignore) so that Package Control will not force the symbolic link into an archive which is likely what is preventing it from resolving to the hard file.

The other option would be to just overwrite the top-level color scheme file with the generated one every time we patch -- but this is dangerous since devs might not realize the file is generated and start editing it. This was the motivation behind creating a symbolic link, also so that existing users would not experience a missing file error message.

**Comment by bathos** [comment]
@blake-regalia I’ve never looked into how this is done, but fairly often I’ve seen packages display a notice file to communicate new features or breaking changes on upgrade. What are your thoughts on removing the symlink and letting people know how to proceed with a notice like that?

**Comment by blake-regalia** [comment]
Sounds good to me, i'll get this going

**Comment by blake-regalia** [comment]
Fixed in [v2.0.0](https://github.com/bathos/Ecmascript-Sublime/releases/tag/2.0.0)
