### ISSUE TITLE
Add support for interpolated attribute values in HTML / HTML-like template tags without quotation marks

### ISSUE THREAD

**Issue by bensmithett** [bathos/Ecmascript-Sublime#70]
👋 thanks for the excellent package!

Is it possible to support [htm](https://github.com/developit/htm) syntax?

**Expected:**

![htm](https://user-images.githubusercontent.com/771396/61987045-b44afc80-b056-11e9-914f-332043b9e8da.png)

**Current (html syntax)**

![2019-07-27 at 10 13 am](https://user-images.githubusercontent.com/771396/61987158-874b1980-b057-11e9-96ab-11eb5019cf01.png)

It's _almost_ there, but not sure if there's much you can do about this - is it just delegating to sublime's HTML syntax?

**Current (js syntax)**

<img width="410" alt="Screen Shot 2019-07-27 at 10 17 46 am" src="https://user-images.githubusercontent.com/771396/61987208-de50ee80-b057-11e9-8dc6-25bdef9e175d.png">

---

It's [supported in VSCode](https://github.com/developit/htm#improvements-over-jsx) via the [lit-html](https://github.com/Polymer/lit-html) extension, so is there potential to similarly support both here?

Thanks 🙂

**Comment by bathos** [comment]
For most template tag language modes, yes, we just delegate to existing definitions. But iirc, HTML may be one of the exceptional cases where we’re baking in a customized version, so this may be addressable.

The problem you’re running into appears to specifically be about attribute quotation marks. When we get past the interpolated segment, we’re still expecting opening quotation marks for an HTML attribute. The nature of the problem can be seen more clearly if we add quotation marks after — it resumes correctly, then:

![image](https://user-images.githubusercontent.com/6257356/61988325-db211880-afed-11e9-8d1c-a38618fd4530.png)

A bit tangential, but maybe interesting: You mentioned that the lit-html extension for VSCode handles their absence okay. That surprised me slightly since lit-html discourages omitting the quotation marks, normally included because lit-html templates get parsed as real HTML by the browser. It’s a bit of a footgun in that context to omit them (it’s often fine, but may lead to avoidable surprises), so I haven’t noticed the issue myself as a lit-html user:

![image](https://user-images.githubusercontent.com/6257356/61988293-8087bc80-afed-11e9-9bdd-3ab7a66c10aa.png)

I will take a look at whether we’re baking in our own HTML def here or not and see if this is fixable from there.

**Comment by bathos** [comment]
I missed the second item in your screenshot on the first read, the use of interpolated segments in place of tag names. That’s a bit trickier since the assumption we need to make is weaker. That is, `attr=${}` is a strong signal because we know the sequence must begin with an attribute value (even if it’s the empty string), and we couldn’t possibly be expected to recover if someone did things like `attr=${"'foo'>"}` or `attr="${ 'foo"' }`. In contrast, `<${x}` is not a good indicator of a tag start but there are many other possible continuations there in HTML, some of which even leave the < as chardata. I’ll look into it though.

**Comment by bathos** [comment]
@bensmithett It turned out solving for both cases was possible without the kind of ‘correctness’ concessions I thought would be necessary. I’m gonna wait for a sign off on the PR from Blake since he knows the tagged template stuff much better than I do, but I think it’s likely gonna work.

BTW, for html you can omit the /* syntax: html */ now if the name of the tag is `html`.

**Comment by bensmithett** [comment]
@bathos amazing, thanks!

**Comment by blake-regalia** [comment]
it is possible - i can do some black magic and have the embedded HTML syntax explicitly allow interpolated elements to act as unquoted attribute values. This opens up pandora's box a tiny bit since we would also want to consider all embedded contexts that should recover from interpolated elements, but i definitely see the value in making this work for markup languages. We wouldn't try to recover from the situations @bathos describes but we can at least cover all the cases you would want to interpolate a word,, tag attribute or value.

**Comment by blake-regalia** [comment]
**Update** just saw the two prev posts and the PR. Will check it out now.

**Comment by blake-regalia** [comment]
Fixed in [v2.1.2](https://github.com/bathos/Ecmascript-Sublime/releases/tag/2.1.2). Interpolation now supports tag names, attribute names, attribute values, and text node values.
